config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :comments
  resources :subjects
  resources :questions do
    resources :answers do
      get "/comments", to: 'questions#fetch_comments', on: :member
    end
    get "/comments", to: 'questions#fetch_comments', on: :member
  end
  resources :tags
  root :to => "subjects#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, :counter_cache => true
  has_many :answers,dependent: :destroy
  has_many :comments, as: :commentable
  has_many :tagged_services
  has_many :tags, through: :tagged_services
  validates :question, :presence => true

  scope :active, -> { where(active: 'true') }
  scope :inactive, -> { where(inactive: 'true') }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fetch_comments
    @comments = Question.find_by_id(params[:id]).try(:comments)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:question, :subject_id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question, :html => {:class => "form-horizontal question"} do |f| %>

    <% if @question.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@question.errors.count, "error") %> prohibited this question from
              being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @question.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :question, :class => 'control-label col-lg-2' %>
      <div class="col-lg-2">
        <%= f.text_field :question, :class => 'form-control' %>
      </div>
      <%= f.error_span(:question) %>
    </div>
    <div class="form-group">
      <%= f.label :subject, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.collection_select :subject_id, Subject.all, :id, :name, include_blank: false, :class => 'form-control' %>
      </div>
      <%= f.error_span(:name) %>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    questions_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/fetch_comments.js.erb
$("#comments-body").html("<%= j render "comments/comments" %>")
$("#commentModal").modal("toggle");

app/views/questions/index.html.erb
<%- model_class = Question -%>
<div class="custom-header">
  <div class="row">
    <div class="col-lg-6"><h4><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4></div>
    <div class="col-lg-6">
      <%= link_to t('.new', :default => t("helpers.links.new_question")),
                  new_question_path,
                  :class => 'btn btn-primary btn-sm pull-right' %>
    </div>
  </div>
</div>
<div class="row">
  <% @questions.each do |question| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <span class="pull-right badge"><%= question.subject.name %></span>
          <div class="caption">
            <h3 class="question_text"><%= question.question %></h3>
            <p class="question_<%= question.id %>">
              <%= link_to "#{question.comments.count} Comment(s)", comments_question_path(question.id), remote: true %>
            </p>
            <p>
              <button type="button" data-id="<%= question.id %>" class="btn btn-xs btn-info comment_link" data-toggle="modal" data-target="#myModal">Comment</button>
              <%#= link_to t('Comment', :default => t("helpers.links.comment")),
                          question_answers_path(question.id), :class => 'btn btn-default btn-xs btn-info' %>
              <%= link_to t('Answer', :default => t("helpers.links.answer")),
                          new_question_answer_path(question.id), :class => 'btn btn-default btn-xs btn-success' %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_question_path(question), :class => 'btn btn-default btn-xs btn-warning' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          question_path(question),
                          :method => :delete,
                          :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                          :class => 'btn btn-xs btn-danger' %>
            </p>
          </div>
          <div class="caption pull-right">
            <%= link_to t('View All Answers', :default => t("helpers.links.view_answers")),
                        question_answers_path(question.id), :class => 'btn btn-default btn-xs btn-success' %>
          </div>
        </div>
      </div>
  <% end %>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <%= form_tag comments_path, :method => :post, :class => 'form-group', remote: true do %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="comment_form">Question ???</h4>
          </div>
          <div class="modal-body">
            <label for="comment">Comment:</label>
            <%= text_area_tag 'comment[comment]', nil, rows: 5, cols: 10, class: 'form-control comment_text' %>
            <%= hidden_field_tag 'comment[commentable_id]' %>
            <%= hidden_field_tag 'comment[commentable_type]', "Question" %>
          </div>
          <div class="modal-footer">
            <%= submit_tag 'Save', class: "btn btn-primary" %>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
      <% end %>
    </div>

  </div>
</div>
<!-- Comments Modal -->

<div class="modal fade" id="commentModal" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="comment_form">Comments</h4>
      </div>
      <div class="modal-body" id="comments-body"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:question) %>:</strong></dt>
  <dd><%= @question.question %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subject) %>:</strong></dt>
  <dd><%= @question.subject.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              questions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_question_path(@question), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              question_path(@question),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>